{application,mariaex,
             [{registered,[]},
              {description,"Pure elixir database driver for MariaDB / MySQL."},
              {applications,[kernel,stdlib,elixir,logger,decimal]},
              {vsn,"0.4.3"},
              {modules,['Elixir.Mariaex.Cache','Elixir.Mariaex.Coder',
                        'Elixir.Mariaex.Coder.Utils',
                        'Elixir.Mariaex.Connection',
                        'Elixir.Mariaex.Connection.Tcp',
                        'Elixir.Mariaex.Error','Elixir.Mariaex.Messages',
                        'Elixir.Mariaex.Protocol','Elixir.Mariaex.Result']}]}.